{% set build_number = environ.get("build_no",0) %}
{% set gpf_version = environ.get('gpf_version','2015.0.0') %}

package:
  name: gpf_gpfjs
  version: {{ gpf_version }}

source:
  path: /wd/sources/gpfjs
  folder: gpfjs/

build:
  number: {{ build_number }}
  noarch: generic
